highlighter: rouge
markdown: kramdown
rdiscount:
  extensions: [smart]
permalink: :title.html
paginate: 5
gems: [jekyll-paginate]
port: 4000
safe: true
url: http://sitaramshelke.me
author: Sitaram Shelke

# edit this section with your information
# biomadeira.github.io - all contents run on /vitae/
# for a normal use at the base of the server change it to "/"
baseurl: /resume/
title: Sitaram's Resume
name: Sitaram Shelke
email: sitaramshelke@gmail.com
email_full: mailto:sitaramshelke@gmail.com
website: sitaramshelke.me
website_full: https://sitaramshelke.me
github: sitaramshelke
twitter: sitaramshelke
#tel: +44 0000 000000
#tel_full: tel:+440000000000
google_maps: 'https://www.google.co.in/maps/place/Bavdhan,+Pune,+Maharashtra/'
address: Bavdhan Gaon
postcode: 411021
city: Pune
country: India
google_analytics: UA-72761937-1

# needed for travis-ci build
#exclude: [vendor]
